### ISSUE TITLE
如果在非服务器上运行了yarn run start会怎么样......

### ISSUE THREAD

**Issue by Bambusaceae** [AimonaStudio/luogu-drawer#1]
RT...
Blow up?

**Comment by Himself65** [comment]
这个东西原本就是给服务器用的

**Comment by Himself65** [comment]
非服务器也一样

**Comment by Bambusaceae** [comment]
好的，谢谢

**Comment by Bambusaceae** [comment]
想想要不要把面包的头像画上去......

**Comment by Himself65** [comment]
gkd！

by Himself65
________________________________
发件人: Bambusoideae <notifications@github.com>
发送时间: Monday, December 30, 2019 6:46:52 PM
收件人: AimonaStudio/luogu-drawer <luogu-drawer@noreply.github.com>
抄送: 扩散性百万甜面包 <himself65@outlook.com>; State change <state_change@noreply.github.com>
主题: Re: [AimonaStudio/luogu-drawer] 如果在非服务器上运行了yarn run start会怎么样...... (#1)


想想要不要把面包的头像画上去......

―

**Comment by Bambusaceae** [comment]
等会我做完作业把它更新一下，毕竟域名、前端什么的都有变化。

**Comment by Bambusaceae** [comment]
没辙了
